M48
; DRILL file {KiCad (6.0.8)} date Mon Feb 13 22:44:56 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-13T22:44:56-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X99.61Y-77.835
X105.39Y-77.835
T2
X109.96Y-49.9
X109.96Y-56.7
T0
M30
